[deps]
ColorSchemeTools = "d3e213a1-5e82-5c18-bb32-2a58a99f8c46"
SPJ_Project = "eb2b0a40-910f-4951-b6ed-121d849dc02f"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
